/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        tertiary: "var(--tertiary)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "inverse-surface": "var(--inverse-surface)",
        "primary-fixed": "var(--primary-fixed)",
        secondary: "var(--secondary)",
        surface: "var(--surface)",
        "error-container": "var(--error-container)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface-container-high": "var(--surface-container-high)",
        "on-error": "var(--on-error)",
        "on-surface": "var(--on-surface)",
        "on-primary": "var(--on-primary)",
        "surface-container-low": "var(--surface-container-low)",
        "primary-container": "var(--primary-container)",
        "surface-bright": "var(--surface-bright)",
        "on-secondary-container": "var(--on-secondary-container)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "surface-variant": "var(--surface-variant)",
        "outline-variant": "var(--outline-variant)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-background": "var(--on-background)",
        "on-secondary": "var(--on-secondary)",
        primary: "var(--primary)",
        "secondary-container": "var(--secondary-container)",
        "secondary-fixed": "var(--secondary-fixed)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "tertiary-container": "var(--tertiary-container)",
        outline: "var(--outline)",
        "on-primary-container": "var(--on-primary-container)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "surface-container": "var(--surface-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-tertiary": "var(--on-tertiary)",
        error: "var(--error)",
        "inverse-primary": "var(--inverse-primary)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-error-container": "var(--on-error-container)",
        "surface-tint": "var(--surface-tint)",
        "surface-dim": "var(--surface-dim)",
        background: "var(--background)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        sm: "8px",
        "margin-desktop": "48px",
        md: "16px",
        xs: "4px",
        xl: "32px",
        gutter: "24px",
        "margin-mobile": "16px",
        unit: "4px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
