/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#574500",
        "on-primary-fixed": "#00201d",
        "on-secondary-fixed-variant": "#92002a",
        "inverse-on-surface": "#f2f1ee",
        tertiary: "#735c00",
        "on-secondary-fixed": "#40000d",
        "inverse-surface": "#2f312f",
        "primary-fixed": "#89f5e7",
        secondary: "#b90538",
        surface: "#faf9f6",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#ffb2b7",
        "surface-container-high": "#e9e8e5",
        "on-error": "#ffffff",
        "on-surface": "#1a1c1a",
        "on-primary": "#ffffff",
        "surface-container-low": "#f4f3f0",
        "primary-container": "#008378",
        "surface-bright": "#faf9f6",
        "on-secondary-container": "#fffbff",
        "tertiary-fixed-dim": "#eec200",
        "primary-fixed-dim": "#6bd8cb",
        "surface-variant": "#e3e2df",
        "outline-variant": "#bcc9c6",
        "surface-container-highest": "#e3e2df",
        "on-background": "#1a1c1a",
        "on-secondary": "#ffffff",
        primary: "#00685f",
        "secondary-container": "#dc2c4f",
        "secondary-fixed": "#ffdadb",
        "tertiary-fixed": "#ffe083",
        "on-tertiary-fixed": "#231b00",
        "tertiary-container": "#cea700",
        outline: "#6d7a77",
        "on-primary-container": "#f4fffc",
        "on-primary-fixed-variant": "#005049",
        "surface-container": "#efeeeb",
        "on-tertiary-container": "#4e3e00",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "inverse-primary": "#6bd8cb",
        "on-surface-variant": "#3d4947",
        "on-error-container": "#93000a",
        "surface-tint": "#006a61",
        "surface-dim": "#dbdad7",
        background: "#faf9f6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        sm: "8px",
        "margin-desktop": "48px",
        md: "16px",
        xs: "4px",
        xl: "32px",
        gutter: "24px",
        "margin-mobile": "16px",
        unit: "4px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
